[features]
seeds = false
skip-lint = false

[programs.devnet]
solrem_prediction_markets = "SoLrEmPrEdIcTiOnMaRkEtS1111111111111111111"

[programs.mainnet]
solrem_prediction_markets = "SoLrEmPrEdIcTiOnMaRkEtS1111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
