/**
 * Supabase Client Configuration
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    'Missing Supabase environment variables. Please check .env.local',
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});

// Database Types (will be auto-generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          wallet_address: string;
          username: string;
          bio: string;
          avatar_url: string | null;
          rank: number;
          total_rem_points: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['users']['Row'],
          'id' | 'created_at' | 'updated_at'
        >;
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      sleep_records: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          score: number;
          rem_score: number;
          deep_score: number;
          efficiency: number;
          duration_hours: number;
          latency_minutes: number;
          waso_minutes: number;
          raw_data: any;
          device_id: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['sleep_records']['Row'],
          'id' | 'created_at'
        >;
        Update: Partial<
          Database['public']['Tables']['sleep_records']['Insert']
        >;
      };
      devices: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          type: 'GARMIN' | 'WHOOP' | 'CUDIS';
          connected: boolean;
          last_sync: string | null;
          battery_level: number | null;
          access_token: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['devices']['Row'],
          'id' | 'created_at'
        >;
        Update: Partial<Database['public']['Tables']['devices']['Insert']>;
      };
      markets: {
        Row: {
          id: string;
          question: string;
          description: string;
          rules: string;
          category: 'Personal' | 'Global' | 'Challenge';
          ends_at: string;
          pool_size: number;
          liquidity: number;
          yes_percent: number;
          no_percent: number;
          volume: number;
          status: 'active' | 'resolved' | 'cancelled';
          on_chain_address: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['markets']['Row'],
          'id' | 'created_at'
        >;
        Update: Partial<Database['public']['Tables']['markets']['Insert']>;
      };
      user_bets: {
        Row: {
          id: string;
          user_id: string;
          market_id: string;
          amount: number;
          position: 'YES' | 'NO';
          entry_price: number;
          potential_payout: number;
          status: 'OPEN' | 'WON' | 'LOST';
          transaction_signature: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['user_bets']['Row'],
          'id' | 'created_at'
        >;
        Update: Partial<Database['public']['Tables']['user_bets']['Insert']>;
      };
    };
  };
}
