import {
  Device,
  LeaderboardEntry,
  Market,
  ResourceItem,
  SleepData,
  UserBet,
  UserProfile,
} from './types';

const HOUR = 60 * 60 * 1000;
const now = Date.now();

export const MOCK_SLEEP_HISTORY: SleepData[] = [
  { date: 'May 03', score: 71, remScore: 63, deepScore: 69, efficiency: 84, durationHours: 6.4, latencyMinutes: 18, wasoMinutes: 44 },
  { date: 'May 04', score: 76, remScore: 70, deepScore: 74, efficiency: 87, durationHours: 6.9, latencyMinutes: 14, wasoMinutes: 34 },
  { date: 'May 05', score: 82, remScore: 80, deepScore: 77, efficiency: 90, durationHours: 7.3, latencyMinutes: 11, wasoMinutes: 26 },
  { date: 'May 06', score: 79, remScore: 74, deepScore: 75, efficiency: 88, durationHours: 7.1, latencyMinutes: 16, wasoMinutes: 29 },
  { date: 'May 07', score: 87, remScore: 89, deepScore: 82, efficiency: 93, durationHours: 7.8, latencyMinutes: 9, wasoMinutes: 20 },
  { date: 'May 08', score: 84, remScore: 81, deepScore: 79, efficiency: 91, durationHours: 7.5, latencyMinutes: 13, wasoMinutes: 22 },
  { date: 'May 09', score: 90, remScore: 92, deepScore: 84, efficiency: 95, durationHours: 8.0, latencyMinutes: 7, wasoMinutes: 16 },
  { date: 'May 10', score: 88, remScore: 86, deepScore: 81, efficiency: 92, durationHours: 7.7, latencyMinutes: 12, wasoMinutes: 19 },
  { date: 'May 11', score: 92, remScore: 94, deepScore: 87, efficiency: 96, durationHours: 8.2, latencyMinutes: 6, wasoMinutes: 12 },
  { date: 'Today', score: 94, remScore: 96, deepScore: 89, efficiency: 97, durationHours: 8.4, latencyMinutes: 5, wasoMinutes: 9 },
];

export const MOCK_MARKETS: Market[] = [
  {
    id: 'm1',
    question: 'Will your REM share clear 25% tonight?',
    description: 'A high-volume personal market tied to your primary wearable session and REM-heavy recovery patterns.',
    rules: 'Resolves YES if the primary connected device reports REM sleep percentage above 25.0% for the next completed sleep session.',
    endsAt: new Date(now + 12 * HOUR),
    poolSize: 145.2,
    liquidity: 4500,
    yesPercent: 45,
    noPercent: 55,
    volume: 1200,
    category: 'Personal',
  },
  {
    id: 'm2',
    question: 'Will SolREM global average score finish above 80?',
    description: 'A macro market on the average overnight score of all synced wallets in the network.',
    rules: 'Resolves YES if the computed global average sleep score of active users exceeds 80.0 by the daily close.',
    endsAt: new Date(now + 6 * HOUR),
    poolSize: 520.5,
    liquidity: 12000,
    yesPercent: 62,
    noPercent: 38,
    volume: 5400,
    category: 'Global',
  },
  {
    id: 'm3',
    question: 'Will @sleep_king log more than 8.0h tonight?',
    description: 'A challenge market on the leaderboard leader holding their weekly streak.',
    rules: 'Resolves YES if @sleep_king logs total sleep duration greater than 8.0 hours for the next tracked night.',
    endsAt: new Date(now + 4 * HOUR),
    poolSize: 85.1,
    liquidity: 2000,
    yesPercent: 30,
    noPercent: 70,
    volume: 800,
    category: 'Challenge',
  },
  {
    id: 'm4',
    question: 'Will your sleep efficiency stay above 92%?',
    description: 'Momentum market focused on consistency and fragmentation control rather than pure duration.',
    rules: 'Resolves YES if sleep efficiency for the next completed session is at least 92.0%.',
    endsAt: new Date(now + 10 * HOUR),
    poolSize: 214.8,
    liquidity: 6800,
    yesPercent: 57,
    noPercent: 43,
    volume: 2600,
    category: 'Personal',
  },
  {
    id: 'm5',
    question: 'Will weekend users average 7.5h+ total duration?',
    description: 'A broad crowd market measuring whether weekend sleep debt is finally getting paid back.',
    rules: 'Resolves YES if average total sleep duration among all synced weekend sessions is 7.5 hours or higher.',
    endsAt: new Date(now + 18 * HOUR),
    poolSize: 402.4,
    liquidity: 9300,
    yesPercent: 54,
    noPercent: 46,
    volume: 6100,
    category: 'Global',
  },
  {
    id: 'm6',
    question: 'Will deep sleep clear 90 minutes for your next session?',
    description: 'A high-conviction personal line for users optimizing cooling, supplementation, and training load.',
    rules: 'Resolves YES if the next completed sleep session includes more than 90 minutes of deep sleep.',
    endsAt: new Date(now + 8 * HOUR),
    poolSize: 178.3,
    liquidity: 5200,
    yesPercent: 41,
    noPercent: 59,
    volume: 1900,
    category: 'Personal',
  },
  {
    id: 'm7',
    question: 'Will Team No-Caffeine beat Team Night-Owl on score?',
    description: 'Community challenge comparing two large cohorts battling for the best aggregate nightly score.',
    rules: 'Resolves YES if Team No-Caffeine posts a higher average score than Team Night-Owl in the current challenge window.',
    endsAt: new Date(now + 14 * HOUR),
    poolSize: 735.9,
    liquidity: 16400,
    yesPercent: 68,
    noPercent: 32,
    volume: 9800,
    category: 'Challenge',
  },
  {
    id: 'm8',
    question: 'Will recovery ring holders push REM index to a weekly high?',
    description: 'A thematic market tracking whether high-signal device users lift the protocol REM index to a new peak.',
    rules: 'Resolves YES if the protocol REM index posts its highest daily print of the current week.',
    endsAt: new Date(now + 20 * HOUR),
    poolSize: 618.6,
    liquidity: 14800,
    yesPercent: 49,
    noPercent: 51,
    volume: 7400,
    category: 'Global',
  },
];

export const MOCK_USER_BETS: UserBet[] = [
  { marketId: 'm1', amount: 0.8, position: 'YES', entryPrice: 38, potentialPayout: 2.11, status: 'OPEN' },
  { marketId: 'm2', amount: 1.35, position: 'NO', entryPrice: 33, potentialPayout: 4.09, status: 'OPEN' },
  { marketId: 'm4', amount: 0.55, position: 'YES', entryPrice: 51, potentialPayout: 1.08, status: 'OPEN' },
  { marketId: 'm6', amount: 0.42, position: 'NO', entryPrice: 57, potentialPayout: 0.74, status: 'OPEN' },
  { marketId: 'm7', amount: 1.9, position: 'YES', entryPrice: 61, potentialPayout: 3.11, status: 'OPEN' },
];

export const MOCK_DEVICES: Device[] = [
  { id: 'd1', name: 'Garmin Fenix 7', type: 'GARMIN', connected: true, lastSync: new Date(now - 9 * 60 * 1000), batteryLevel: 78 },
  { id: 'd2', name: 'Whoop 4.0', type: 'WHOOP', connected: true, lastSync: new Date(now - 21 * 60 * 1000), batteryLevel: 64 },
  { id: 'd3', name: 'Oura Ring Gen3', type: 'CUDIS', connected: true, lastSync: new Date(now - 37 * 60 * 1000), batteryLevel: 81 },
  { id: 'd4', name: 'CUDIS Ring', type: 'CUDIS', connected: false, lastSync: null },
  { id: 'd5', name: 'Apple Watch Sync Bridge', type: 'GARMIN', connected: false, lastSync: new Date(now - 5 * HOUR) },
  { id: 'd6', name: 'Whoop Trial Band', type: 'WHOOP', connected: false, lastSync: null },
];

export const USER_PROFILE: UserProfile = {
  username: 'SolSleeper',
  bio: 'REM-heavy routines, evening wind-down experiments, and a mild obsession with recovery alpha.',
  avatarUrl: '',
  rank: 7,
  solBalance: 12.45,
  remPoints: 12480,
  streak: 29,
};

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, username: 'SLEEP_KING', points: 19840, accuracy: 97.8, streak: 44, marketsWon: 128, walletAddress: '9q1x...alpha' },
  { rank: 2, username: 'CIRCADIAN_Q', points: 19110, accuracy: 96.9, streak: 38, marketsWon: 119, walletAddress: '7ptv...beta' },
  { rank: 3, username: 'DEEP_MODE', points: 18570, accuracy: 96.1, streak: 35, marketsWon: 111, walletAddress: '8nfy...gamma' },
  { rank: 4, username: 'WHOOPMAXXER', points: 17620, accuracy: 95.7, streak: 31, marketsWon: 102, walletAddress: '4rrt...delta' },
  { rank: 5, username: 'SLOWWAVE', points: 16990, accuracy: 95.2, streak: 28, marketsWon: 97, walletAddress: '6ffm...eps' },
  { rank: 6, username: 'MOONLATENCY', points: 16340, accuracy: 94.6, streak: 22, marketsWon: 92, walletAddress: '5krn...zeta' },
  { rank: 7, username: 'SOLSLEEPER', points: 15880, accuracy: 94.2, streak: 29, marketsWon: 88, walletAddress: '2vtn...eta' },
  { rank: 8, username: 'NAPSTRATEGY', points: 15220, accuracy: 93.9, streak: 20, marketsWon: 81, walletAddress: '3kzu...theta' },
  { rank: 9, username: 'POLYPHASICX', points: 14600, accuracy: 93.1, streak: 18, marketsWon: 77, walletAddress: '1yga...iota' },
  { rank: 10, username: 'REMCHASER', points: 13950, accuracy: 92.8, streak: 16, marketsWon: 70, walletAddress: '8sna...kappa' },
  { rank: 11, username: 'NIGHTSTACK', points: 13340, accuracy: 92.2, streak: 14, marketsWon: 64, walletAddress: '7rqe...lambda' },
  { rank: 12, username: 'DREAMARC', points: 12710, accuracy: 91.7, streak: 12, marketsWon: 59, walletAddress: '6qxm...mu' },
];

export const MOCK_RESOURCES: ResourceItem[] = [
  {
    id: 'r1',
    type: 'ARTICLE',
    title: 'The Science of REM: Why Dreaming Matters',
    description: 'Understand how REM consolidates memory, sharpens pattern recognition, and stabilizes mood under stress.',
    author: 'Dr. Matt Walker',
    duration: '6 min read',
    link: 'https://google.com',
    thumbnailColor: 'from-blue-600 to-indigo-900',
  },
  {
    id: 'r2',
    type: 'VIDEO',
    title: 'Sleep Toolkit: Tools for Perfect Sleep',
    description: 'High-signal interventions for circadian timing, light exposure, and pre-sleep downshifting.',
    author: 'Huberman Lab',
    duration: '15:20',
    link: 'https://youtube.com',
    thumbnailColor: 'from-gray-900 to-black',
  },
  {
    id: 'r3',
    type: 'PODCAST',
    title: 'Caffeine, Alcohol & Sleep Architecture',
    description: 'A practical breakdown of how timing and dose degrade sleep stages even when duration looks fine.',
    author: 'Peter Attia',
    duration: '45:00',
    link: 'https://spotify.com',
    thumbnailColor: 'from-green-900 to-emerald-950',
  },
  {
    id: 'r4',
    type: 'ARTICLE',
    title: 'Temperature Control for Deep Sleep',
    description: 'Why core body temperature drop is the hidden unlock for cleaner deep sleep transitions.',
    author: 'Sleep Foundation',
    duration: '4 min read',
    link: 'https://google.com',
    thumbnailColor: 'from-orange-700 to-red-900',
  },
  {
    id: 'r5',
    type: 'VIDEO',
    title: 'Recovery Routines Used by Elite Endurance Athletes',
    description: 'A concise field guide to late-evening hydration, nutrition, and light management for better overnight recovery.',
    author: 'Training Peaks',
    duration: '12:48',
    link: 'https://youtube.com',
    thumbnailColor: 'from-cyan-800 to-slate-950',
  },
  {
    id: 'r6',
    type: 'ARTICLE',
    title: 'How to Interpret Sleep Efficiency Without Fooling Yourself',
    description: 'A sharper way to read efficiency alongside latency and wake-after-sleep-onset.',
    author: 'Quantified Self',
    duration: '8 min read',
    link: 'https://google.com',
    thumbnailColor: 'from-fuchsia-900 to-zinc-950',
  },
  {
    id: 'r7',
    type: 'PODCAST',
    title: 'Melatonin, Light, and the Myth of Catch-Up Sleep',
    description: 'A nuanced conversation about sleep debt, phase shifting, and why weekend fixes often fail.',
    author: 'FoundMyFitness',
    duration: '38:12',
    link: 'https://spotify.com',
    thumbnailColor: 'from-violet-900 to-black',
  },
  {
    id: 'r8',
    type: 'ARTICLE',
    title: 'Blueprint for a 30-Day REM Optimization Sprint',
    description: 'A structured self-experiment covering bedtime consistency, alcohol removal, and ambient cooling.',
    author: 'SolREM Research',
    duration: '10 min read',
    link: 'https://google.com',
    thumbnailColor: 'from-lime-700 to-emerald-950',
  },
];
